import { EngineRunner } from "./EngineRunner";

export class FakeRunner implements EngineRunner {
  async run(prompt: string): Promise<string> {
    if (prompt.includes("online marketplace")) {
      return `
Generate a product listing for an online marketplace.

TITLE: Sample Marketplace Title
DESCRIPTION:
This is a fake marketplace description.
`;
    }

    if (prompt.includes("job application")) {
      return `
TITLE: Sample title
DESCRIPTION:
This is a placeholder response generated by the engine.
`;
    }

    return "Deterministic test output";
  }
}
