// tests/helpers/fakeEngine.ts

import { EngineMode } from "@/engine/core/mode";
import { EngineInput, EngineOutput } from "@/engine/core/types";


/**
 * Runs a deterministic version of the engine for testing purposes.
 * Does NOT call AI — returns a fixed output formatted by the mode.
 */
export async function runFakeEngine<TContent>(
  mode: EngineMode<TContent>,
  input: EngineInput<TContent>
): Promise<EngineOutput> {
  // Build a deterministic raw string based on the mode
  let raw: string;
    console.log("Mode ID:", mode.id);
  switch (mode.id) {
    case "marketplace": 
        const { productName, description, price, platform } = input.content as any;
        raw = `
    Generate a product listing for an online marketplace.

    Item: ${productName}
    Description: ${description}
    Price: ${price ?? "Not specified"}
    Platform: ${platform ?? "Not specified"}

    Tone: ${input.tone}
    Audience: ${input.audience}
    `;
        break;

    case "job":
        raw = `
    TITLE: Sample title
    DESCRIPTION:
    This is a placeholder response generated by the engine.
    `;
        break;

    default:
        raw = "Deterministic test output";
}

  // Format it using the mode’s formatOutput method
  return mode.formatOutput(raw);
}
