import { EngineInput, EngineOutput } from "./types"
import { EngineMode } from "./mode"

export async function runEngine<TContent>(
  mode: EngineMode<TContent>,
  input: EngineInput<TContent>
): Promise<EngineOutput> {
  const prompt = mode.buildPrompt(input)

  let fakeResponse: string;

  if(mode.name === "Marketplace Mode") {
    fakeResponse = `
  Generate a product listing for an online marketplace.

  Item: ${input.content.productName}
  Description: ${input.content.description}
  Price: ${input.content.price ?? "Not specified"}
  Platform: ${input.content.platform ?? "Not specified"}

  Tone: ${input.tone}
  Audience: ${input.audience}
    `;
      } else {
    fakeResponse = `
TITLE: Sample title
DESCRIPTION:
This is a placeholder response generated by the engine.
`;
  }

  return mode.formatOutput(fakeResponse);
}
