import { EngineInput, EngineOutput } from "./types"
import { EngineMode } from "./mode"

export async function runEngine<TContent>(
  mode: EngineMode<TContent>,
  input: EngineInput<TContent>
): Promise<EngineOutput> {
  const prompt = mode.buildPrompt(input)

  // Placeholder (AI will go here)
  const fakeResponse = `
TITLE: Sample title
DESCRIPTION:
This is a placeholder response generated by the engine.
`

  return mode.formatOutput(fakeResponse)
}
